gaul/modernizer-maven-plugin

pom.xml, src/main/java/org/gaul/modernizer_maven_plugin/Modernizer.java, src/main/resources/modernizer.xml, src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
These are (almost) always replaceable with the javax.inject variants, which would also
work with other DI frameworks.
=> Add violations for com.google.inject.Inject and com.google.inject.Provider

src/main/java/org/gaul/modernizer_maven_plugin/Modernizer.java, src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
This adds support for flagging violations for wrong annotation classes. This is a requirement for #23.
Note that the test does not rely on any specific invalid annotation, but uses its own dummy annotation.
=> Check annotation classes for violations

src/main/resources/modernizer.xml, src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Details in the commit message:
Guava provides three versions of Preconditions.checkNotNull:
- One that doesn't take a custom exception message.
- One that lazily converts an arbitrary object into an exception message, using
String#valueOf, if necessary.
- One that constructs an exception message based on a given format pattern and
zero or more arguments.
The third one has no equally-convenient (i.e. concise) counterpart in any
version of Java. But the first two do, in Java 7 and 8, respectively:
- Java 8 allows one to provide a Supplier for the lazy message construction,
which support for lambda expressions makes trivial.
- Strictly speaking Java 7 also provides an alternative for the second variant,
but it's more restricted signature means that it doesn't have the nice lazy
string …
=> Detect two variations of Preconditions.checkNotNull

src/main/resources/modernizer.xml
Spring supports @Inject as well so I think it should be recommended to use it instead.
=> Add rule: Prefer @Inject over @Autowired

README.md, src/main/java/org/gaul/modernizer_maven_plugin/ModernizerMojo.java
This change allows one to specify exclusions as part of the plugin configuration. Example:
<configuration> 
<exclusions>    
<exclusion>org/joda/time/DateTime."&lt;init&gt;":(J)V</exclusion>
</exclusions>   
</configuration
This is more convenient than the `<exclusionsFile>` setting when one wishes to suppress certain violations across a multi-module build, because the plugin configuration can be placed in the parent POM and be made to apply to all submodules.
(The `<exclusionsFile>`, by contrast, either requires one to specify an absolute file, or create many violation files, one for each `pom.xml` in the build, all with the same relative path. I'm aware that that the exclusions file can also be read from the plugin's classpath, but that'd require me to package the violations file in a …
=> Add support for specifying exclusions in the POM.

src/main/resources/modernizer.xml, src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Adding violations for `Collections.EMPTY_LIST`, `EMPTY_MAP`, and `EMPTY_SET` to prefer the more modern `emptyList()`, etc. methods which are actually type safe.
=> #57 Violation for EMPTY Collections constants

src/main/resources/modernizer.xml
the current release suggest to use java.lang.UnsignedLongs that does not exists
=> com.google.common.primitives.UnsignedLongs replacements are in java.lang.Long

README.md, src/main/java/org/gaul/modernizer_maven_plugin/ModernizerMojo.java, src/main/java/org/gaul/modernizer_maven_plugin/Utils.java, src/test/java/org/gaul/modernizer_maven_plugin/UtilsTest.java
Empty lines and lines starting with `#` will be ignored.
Fixes #27
=> Allow comments in exclusion file

src/main/resources/modernizer.xml, src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Since Java 8 there are java.util.Collections alternatives for
* unmodifiableNavigableMap
* synchronizedNavigableMap
* unmodifiableNavigableSet
* synchronizedNavigableSet
=> Add violations for Guava NavigableMap/Set methods

modernizer-maven-annotations/pom.xml
This names modernizer-maven-annotations, so it can be used as
a dependency in JMPS. This fixes #93.
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>
=> Add Automatic-Module-Name header

modernizer-maven-annotations/pom.xml
This patch uses a combination of modulemaker-maven-plugin and
multi-release jar (JEP-238) to make modernizer-maven-annotations
a full JPMS module. For older JVM versions there is no impact,
as the class is not visible there.
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>
=> Add JPMS module-info

modernizer-maven-plugin/src/main/resources/modernizer.xml, modernizer-maven-plugin/src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Compare [JDK 11](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/InputStream.html) and [JDK 12](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/InputStream.html).
=> Don't suggest java.io.InputStream.skipNBytes(long) before JDK 12

README.md, modernizer-maven-plugin/pom.xml, modernizer-maven-plugin/src/it/issue-28-option-disabled/invoker.properties, modernizer-maven-plugin/src/it/issue-28-option-disabled/pom.xml, modernizer-maven-plugin/src/it/issue-28-option-disabled/src/main/java/org/gaul/it/Generated.java, modernizer-maven-plugin/src/it/issue-28-option-disabled/src/main/java/org/gaul/it/TestClass.java, modernizer-maven-plugin/src/it/issue-28-option-disabled/verify.groovy, modernizer-maven-plugin/src/it/issue-28-option-enabled/invoker.properties, modernizer-maven-plugin/src/it/issue-28-option-enabled/pom.xml, modernizer-maven-plugin/src/it/issue-28-option-enabled/src/main/java/org/gaul/it/Generated.java, modernizer-maven-plugin/src/it/issue-28-option-enabled/src/main/java/org/gaul/it/TestClass.java, modernizer-maven-plugin/src/it/settings.xml, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/ModernizerMojo.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/SuppressGeneratedAnnotationDetector.java
Provide an implementation for #28.
This is a rather dirty implementation. Based on the already existing suppression filter. There is a lot of duplicated code right now and no test.
Should this PR be improved or can it be accepted as is?
Improving this PR would probably take some time. I have some ideas, but I would like to check them with you first @gaul. Maybe lets split this. Accept the PR as is and open an issue to track the cleanup and missing test.
=> Ignore classes annotated with `@Generated` #28

modernizer-maven-plugin/src/it/issue-28-option-disabled/verify.groovy
test assuming using *nix.  Fixed so this works on both windows and *nix.
File.separator is required for cross platform support.  When using windows, the default is \ which will fail this IT test.  This IT tests is expecting *nix only.  The result here is the same but ensures cross platform usage uses the right file seperator.
=> Modify verify.groovy IT test to support cross platform

modernizer-maven-annotations/pom.xml
Jar plugin version was not defined in parent about this usage.  While mavens super parent pom will address many of the plugins, they are ultimately going to remove that and enforce proper usage.  Also, higher jdk usage will through warnings due to not defining the version.
=> [pom] Add missing version to maven jar plugin at 3.2.0

modernizer-maven-plugin/pom.xml
To support higher jdks
Maven invoker plugin is on groovy 2.2.2 for jdk 6 and 2.4.8 for jdk 7.  It works without question on latest releases.  In order to support higher jdks, this needs to be overridden otherwise builds will fail.  This does not impact the code base and all IT tests run as with before.
=> [pom] Upgrade invoker plugin to latest and override groovy to latest

modernizer-maven-plugin/pom.xml
Changes:
* add direct dependency onto p-u (was auto-inject in Maven 2 but will not be anymore)
* update prerequisite to Maven 3.2.5 (3.0.x was 10+ years ago and is really dead-dead)
* drop Maven 2 artifact dependencies, switch to required version artifacts instead
* move Maven bits to "provided" scope (as they ARE provided at runtime)
Fixes #152
=> Fix p-u and update plugin

modernizer-maven-plugin/src/main/resources/modernizer.xml, modernizer-maven-plugin/src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Also shuffle `Optional` imports to `java.util.Optional`.  Fixes #147.
=> Recommend `Optional::orElseThrow` instead of `get`

modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/ModernizerMojo.java
When using this plugin with maven-3.9.0, `ClassNotFoundException` and `NoClassDefFoundError` are being thrown because it appears like `org.codehaus.plexus.util.StringUtils` is no longer provided by maven.
The only usage of that class was checking a string for empty, refactored that usage to do the empty checks directly.
```
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/StringUtils
at org.gaul.modernizer_maven_plugin.ModernizerMojo.execute (ModernizerMojo.java:193)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
```
```
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.StringUtils
at …
```
=> Remove usage of plexus StringUtils

modernizer-maven-plugin/src/main/resources/modernizer.xml, modernizer-maven-plugin/src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
For #182 
https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/Stack.html
Suggested replacement is Deque, introduced in Java 6
Can I suggest adding some formatting config/automatic formatting so i don't have to manually satisfy checkstyle pedantic requirements.
Also, I couldn't build the annotation module - set to source/target Java 6 - until I change this to Java 8.
=> Add Stack to legacy apis

modernizer-maven-plugin/src/main/resources/modernizer.xml, modernizer-maven-plugin/src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
This doesn't ban all uses of Enumeration though. It only catches code like
``` java
class TpEnumeration implements Enumeration<Object> {
```
Any ideas?
=> Add Enumeration to legacy apis

modernizer-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
Hint for m2e (maven 2 eclipse) to tell it to do nothing with this plugin so users of plugin don't need to setup anything in their pom such as is setup in this plugin already for maven-plugin-plugin regarding m2e.
=> [m2e] Add m2e hint

README.md, modernizer-maven-plugin/pom.xml, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/ModernizerMojo.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/output/CodeClimateOutputer.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/output/LoggerOutputer.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/output/OutputEntry.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/output/OutputFormat.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/output/Outputer.java, pom.xml
The `source` and `target` for the parent pom was changed to `1.7` due to:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project modernizer-maven-plugin: Compilation failure: Compilation failure: 
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
```
=> Add support for different output formats and add codeclimate as an output format

.github/workflows/ci.yml, modernizer-maven-annotations/pom.xml, modernizer-maven-plugin/pom.xml, pom.xml
Concentrate ALL plugin versions in one single place: build/pluginMgmt
Note: plexus-utils was 4.0.0, downgraded it to 3.5.1 to make sure Maven3 compatibility. p-u 4.x is for Maven4 stuff, and while Maven4 is backard compat is fine using p-u 3.5.1, older Maven3 versions may squeak with p-u 4.x. If you target Maven3 compatibility in plugin (and currently you do), better use 3.x line of p-u.
=> Align to Maven 3.6.3, update plugins, tidy up plugin versions.

pom.xml
Changes:
* remove parent POM updated in 2011
* last two plugins version moved to pluginMgmt
* remove obsolete comment (see https://issues.apache.org/jira/browse/MCHECKSTYLE-260)
* drop nx-staging-plugin (is dead)
=> Detach oss parent

modernizer-maven-plugin/src/main/resources/modernizer.xml, modernizer-maven-plugin/src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Java 24 provides [Reader.of(CharSequence)](https://download.java.net/java/early_access/jdk24/docs/api/java.base/java/io/Reader.html#of(java.lang.CharSequence)).
It is preferrable over `StringReader`, as the API notes says:
>[Reader.of(CharSequence)](https://download.java.net/java/early_access/jdk24/docs/api/java.base/java/io/Reader.html#of(java.lang.CharSequence)) provides a method to read from any [CharSequence](https://download.java.net/java/early_access/jdk24/docs/api/java.base/java/lang/CharSequence.html) that may be more efficient than StringReader.
*Disclaimer: I am the original author of `Reader.of(CharSequence)`. My intention of the current PR is to evangelize its use, so applications will run more efficient.*
=> Add violation for StringReader

.github/workflows/ci.yml, modernizer-maven-plugin/src/main/resources/modernizer.xml, modernizer-maven-plugin/src/test/java/org/gaul/modernizer_maven_plugin/ModernizerTest.java
Modern applications should switch from NIO API to NIO2 API to allow for improved performance.
*Disclaimer: I am part of the I/O performance optimization team at OpenJDK. My intention of the current PR is to evangelize its use, so applications will run more efficient.*
=> Add violations for File, Paths, FileInputStream, FileOutputStream, FileReader and FileWriter

modernizer-maven-plugin/src/main/resources/modernizer.xml
The replacement of the new FileInputStream(..., append) methods needs to use the APPEND option, in addition to CREATE and WRITE.
Fixes #309.
=> Fix recommendation for Files.newOutputStream()

modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/ModernizerMojo.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/SuppressGeneratedAnnotationDetector.java, modernizer-maven-plugin/src/main/java/org/gaul/modernizer_maven_plugin/SuppressModernizerAnnotationDetector.java
Files.list() returns a Stream that needs to be closed, otherwise the directory remains open. This can cause file descriptor exhaustion in large projects.
=> Fix file descriptor leaks
